using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using Burmuruk.RPGStarterTemplate.Stats;
using UnityEditor;

namespace Burmuruk.RPGStarterTemplate.Editor.Controls
{
    // Handles registrations generated by ModSetupEditor, including the old named syntax.
    public static class ModStatReferences
    {
        public sealed class Registration
        {
            public int Start, Length, ValueStart, ValueLength;
            public string Value, VariableName;
        }

        // Preserve offsets while ignoring comments and ordinary/verbatim string literals.
        public static string MaskTrivia(string source)
        {
            return Regex.Replace(source,
                @"//[^\r\n]*|/\*[\s\S]*?\*/|@""(?:""""|[^""])*""|""(?:\\.|[^""\\])*""|'(?:\\.|[^'\\])*'",
                m => new string(m.Value.Select(c => c == '\r' || c == '\n' ? c : ' ').ToArray()));
        }

        public static List<Registration> Read(string source)
        {
            string code = MaskTrivia(source);
            var result = new List<Registration>();
            foreach (Match match in Regex.Matches(code,
                @"\bModsList\s*\.\s*AddVariable\s*\(\s*\(\s*Character\s*\)\s*this\s*,\s*(?<value>ModifiableStat\s*\.\s*@?\w+|\(\s*ModifiableStat\s*\)\s*-?\d+)\s*,"))
            {
                int open = code.IndexOf('(', match.Index);
                int depth = 1;
                int end = open + 1;
                for (; end < code.Length && depth > 0; end++)
                {
                    if (code[end] == '(')
                        depth++;
                    else if (code[end] == ')')
                        depth--;
                }
                if (depth != 0)
                    throw new InvalidDataException("Incomplete ModsList.AddVariable call.");
                while (end < code.Length && char.IsWhiteSpace(code[end]))
                    end++;
                if (end >= code.Length || code[end] != ';')
                    throw new InvalidDataException("Expected a ModsList.AddVariable statement.");
                var getter = Regex.Match(code.Substring(match.Index, end - match.Index),
                    @"\(\s*\)\s*=>\s*(?:stats|basicStats)\s*\.\s*(?<name>@?\w+)");
                if (!getter.Success)
                    throw new InvalidDataException("Unsupported getter in ModsList.AddVariable.");
                Group value = match.Groups["value"];
                result.Add(new Registration
                {
                    Start = match.Index,
                    Length = end + 1 - match.Index,
                    ValueStart = value.Index,
                    ValueLength = value.Length,
                    Value = source.Substring(value.Index, value.Length),
                    VariableName = getter.Groups["name"].Value
                });
            }
            return result;
        }

        public static int ResolveId(string expression, EnumRegistry registry)
        {
            Match number = Regex.Match(expression, @"\)\s*(-?\d+)\s*$");
            if (number.Success)
                return int.Parse(number.Groups[1].Value);
            string name = expression.Substring(expression.LastIndexOf('.') + 1).Trim().TrimStart('@');
            // Existing source names belong to the compiled enum, before pending renames.
            foreach (string oldName in Enum.GetNames(typeof(ModifiableStat)))
                if (oldName == name)
                    return Convert.ToInt32(Enum.Parse(typeof(ModifiableStat), oldName));
            var entry = registry.GetEntry(typeof(ModifiableStat), name);
            if (entry == null)
                throw new InvalidDataException($"Cannot resolve ModifiableStat.{name} to an ID.");
            return entry.Id;
        }

        public static string Synchronize(string source, EnumRegistry registry)
        {
            foreach (var call in Read(source).OrderByDescending(c => c.Start))
            {
                int id = ResolveId(call.Value, registry);
                if (id == EnumRegistry.NoneId || !registry.Contains<ModifiableStat>(id))
                    source = source.Remove(call.Start, call.Length);
                else
                    source = source.Remove(call.ValueStart, call.ValueLength)
                        .Insert(call.ValueStart, $"(ModifiableStat){id}");
            }
            return source;
        }

        // Prepare all edits before any writes. Also migrates existing registrations
        // when there are no pending enum changes.
        public static Dictionary<string, string> PrepareUpdates(EnumRegistry registry)
        {
            var updates = new Dictionary<string, string>();
            foreach (string guid in AssetDatabase.FindAssets("t:Script"))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (!path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase) || !File.Exists(path))
                    continue;
                string source = File.ReadAllText(path);
                if (!source.Contains("ModsList"))
                    continue;
                string updated = Synchronize(source, registry);
                if (updated != source)
                    updates.Add(path, updated);
            }
            return updates;
        }
    }
}
